export function buildExtractionPrompt(transcript: string): string {
  return [
    '你是中国《新闻联播》的结构化标注助手。把下面这期联播文字稿做客观的结构化提取，',
    '用于后续的时间序列分析。请忠实于原文，不要臆造、不要复述无关内容，只抽取确有的信息。',
    '',
    '输出一个 JSON 对象，字段名必须严格使用下列英文键（不要改名，尤其不要用 name 代替 term / sector）：',
    '- items：数组，逐条新闻。每条对象：',
    '    ord（整数，从 1 开始，节目播出顺序）；',
    '    segment（枚举，仅限 "leader"=领导动态 / "dev"=发展成就·民生 / "intl"=国际）；',
    '    title（标题）；summary（1-2 句中文摘要）。',
    '- tifa：数组，值得记录的「提法/关键词」（政治语言、政策口径，如「新质生产力」）。每条对象：',
    '    term（归一化提法本身，不带标点）；count（本期出现次数，整数 ≥ 1）。',
    '- sectors：数组，受影响的行业/板块（"信号→行业"的客观映射，宁缺毋滥）。每条对象：',
    '    sector（行业名，如「半导体」）；polarity（枚举，仅限 "bull"=利好 / "bear"=利空 / "neutral"=中性）；',
    '    strength（0 到 1 之间的小数：0 可忽略、0.5 中等、1 主导）。',
    '',
    '示例（仅示意字段名与类型，不要照抄内容）：',
    '{"items":[{"ord":1,"segment":"leader","title":"……","summary":"……"}],',
    ' "tifa":[{"term":"新质生产力","count":2}],',
    ' "sectors":[{"sector":"半导体","polarity":"bull","strength":0.7}]}',
    '',
    '注意：联播是编排过的信号源，编辑选择本身即信息；做客观抽取，判断留给后续环节。',
    '',
    '=== 联播文字稿开始 ===',
    transcript,
    '=== 联播文字稿结束 ===',
  ].join('\n');
}
